import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import React, { useState, useEffect, useRef } from "react";
import { useScroll, motion, useTransform, useMotionValue } from "framer-motion";
import Logo from "../../public/logo.png";
import HomeGallery from "@/components/HomeGallery";

export default function Home() {
  const [scroll, setScroll] = useState(false);
  const { scrollY } = useScroll();
  const y1 = useTransform(scrollY, [400, 0], [400, 0]);
  const y2 = useTransform(scrollY, [100, 0], [10, 80]);

  useEffect(() => {
    window.addEventListener("scroll", () => {
      setScroll(window.scrollY > 100);
    });
  }, []);
  useEffect(() => {
    let vh = window.innerHeight * 0.01;
    document.documentElement.style.setProperty("--vh", `${vh}px`);

    window.addEventListener("resize", () => {
      // We execute the same script as before
      let vh = window.innerHeight * 0.01;
      document.documentElement.style.setProperty("--vh", `${vh}px`);
    });
  }, []);

  const variants = {
    offscreen: {
      opacity: 0,
      scale: 0.1,
      // y: 100,
      // x: -300,
    },
    onscreen: {
      opacity: 1,
      scale: 1,
      // y: 10,
      x: 0,

      transition: {
        type: "easeIn",
        stiffness: 100,
        duration: 1,
        delay: 0.5,
      },
    },
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <nav className={styles.nav}>
          <ul className={styles.navLogo}>GoBuggy | Arcos</ul>
          {/* <Image src={Logo} alt="logo" width={100} height={100} /> */}
          <ul className={styles.navMenu}>Menu</ul>
        </nav>
      </header>

      <motion.main className={styles.main}>
        <motion.div className={styles.heroBg} style={{ y: 0, x: 0 }}>
          <motion.h1
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 1, delay: 0.7 }}
            style={{ y: y1, x: 0 }}
          >
            Aventura
          </motion.h1>
        </motion.div>
        <motion.div
          className={styles.heroMove}
          style={{ y: y2, x: 0 }}
        ></motion.div>
      </motion.main>
      <section className={styles.section}>
        <HomeGallery />
        {/* <motion.h2
          initial="offscreen"
          whileInView="onscreen"
          viewport={{ once: false, amount: 0.5 }}
          variants={variants}
        >
          Divertimento
        </motion.h2> */}
      </section>
    </div>
  );
}
